-- xmake build for MIDITrail (DX11 port)
-- Usage:
--   xmake f -p windows -a x64 -m release   (configure: 64-bit release)
--   xmake                                  (build)   /   xmake -r  (rebuild)
-- Win32 MultiByte app: YNBaseLib + SMIDILib DLLs and the MIDITrail exe.
-- Source is UTF-8 (BOM on compiled files). ImGui comes from xrepo (the package
-- below); only the custom Japanese glyph ranges stay in-tree.

set_project("MIDITrail")
set_xmakever("2.8.0")
set_languages("c++14")   -- matches the .vcxproj (uses std::ptr_fun, removed in C++17)
add_rules("mode.debug", "mode.release")

-- ImGui from xrepo with the DX11 + Win32 backends (no in-tree imgui sources)
add_requires("imgui 1.92.7", {configs = {dx11 = true, win32 = true}})

add_defines("WIN32", "_WINDOWS", "_MBCS")   -- CharacterSet=MultiByte (no Unicode)
add_defines("_HAS_STD_BYTE=0")              -- avoid std::byte vs Windows 'byte' clash

-- default Windows import libs MSBuild links implicitly (xmake does not)
add_syslinks("user32", "gdi32", "shell32", "advapi32", "ole32", "oleaut32",
             "comdlg32", "uuid", "winspool")

if is_mode("release") then
    set_runtimes("MD")
    set_optimize("fastest")
    add_defines("NDEBUG")
else
    set_runtimes("MDd")
    set_symbols("debug")
    add_defines("_DEBUG")
end

target("YNBaseLib")
    set_kind("shared")
    add_defines("_USRDLL", "YNBASELIB_EXPORTS", "_BIND_TO_CURRENT_VCLIBS_VERSION")
    add_includedirs("YNBaseLib")
    add_files("YNBaseLib/dllmain.cpp")
    add_files("YNBaseLib/stdafx.cpp")
    add_files("YNBaseLib/YNBaseLib.cpp")
    add_files("YNBaseLib/YNConfFile.cpp")
    add_files("YNBaseLib/YNErrCtrl.cpp")
    add_files("YNBaseLib/YNErrInfo.cpp")
    add_files("YNBaseLib/YNPathUtil.cpp")

target("SMIDILib")
    set_kind("shared")
    add_deps("YNBaseLib")
    add_defines("_USRDLL", "SMIDILIB_EXPORTS", "_BIND_TO_CURRENT_VCLIBS_VERSION")
    add_includedirs("YNBaseLib", "SMIDILib")
    add_syslinks("winmm", "shlwapi")
    add_files("SMIDILib/dllmain.cpp")
    add_files("SMIDILib/SMBarList.cpp")
    add_files("SMIDILib/SMEvent.cpp")
    add_files("SMIDILib/SMEventMeta.cpp")
    add_files("SMIDILib/SMEventMIDI.cpp")
    add_files("SMIDILib/SMEventSysEx.cpp")
    add_files("SMIDILib/SMEventSysMsg.cpp")
    add_files("SMIDILib/SMEventWatcher.cpp")
    add_files("SMIDILib/SMFileReader.cpp")
    add_files("SMIDILib/SMFPUCtrl.cpp")
    add_files("SMIDILib/SMIDILib.cpp")
    add_files("SMIDILib/SMInDevCtrl.cpp")
    add_files("SMIDILib/SMLiveMonitor.cpp")
    add_files("SMIDILib/SMMsgParser.cpp")
    add_files("SMIDILib/SMMsgQueue.cpp")
    add_files("SMIDILib/SMMsgTransmitter.cpp")
    add_files("SMIDILib/SMNoteList.cpp")
    add_files("SMIDILib/SMOutDevCtrl.cpp")
    add_files("SMIDILib/SMPortList.cpp")
    add_files("SMIDILib/SMRcpConv.cpp")
    add_files("SMIDILib/SMSeqData.cpp")
    add_files("SMIDILib/SMSequencer.cpp")
    add_files("SMIDILib/SMSimpleList.cpp")
    add_files("SMIDILib/SMTrack.cpp")
    add_files("SMIDILib/stdafx.cpp")

target("MIDITrail")
    set_kind("binary")
    add_deps("SMIDILib", "YNBaseLib")
    add_packages("imgui")
    add_defines("_BIND_TO_CURRENT_VCLIBS_VERSION")
    add_includedirs("YNBaseLib", "SMIDILib", "MIDITrail")
    add_syslinks("dxguid", "d3d9", "d3d11", "dxgi", "d3dcompiler", "windowscodecs",
                 "dinput8", "winmm", "XInput", "imagehlp", "shlwapi")
    add_ldflags("/SUBSYSTEM:WINDOWS", {force = true})
    add_files("MIDITrail/DIKeyCtrl.cpp")
    add_files("MIDITrail/DIMouseCtrl.cpp")
    add_files("MIDITrail/DXCamera.cpp")
    add_files("MIDITrail/DXColorUtil.cpp")
    add_files("MIDITrail/DXPrimitive.cpp")
    add_files("MIDITrail/MTGridBox.cpp")
    add_files("MIDITrail/DXH.cpp")
    add_files("MIDITrail/DXPrimitive11.cpp")
    add_files("MIDITrail/DXTexture11.cpp")
    add_files("MIDITrail/MTKeyboard11.cpp")
    add_files("MIDITrail/DXNoteBox11.cpp")
    add_files("MIDITrail/MTNoteRipple11.cpp")
    add_files("MIDITrail/MTNoteLyrics11.cpp")
    add_files("MIDITrail/MTNoteBoxLive11.cpp")
    add_files("MIDITrail/MTNoteRainLive11.cpp")
    add_files("MIDITrail/MTGridBox11.cpp")
    add_files("MIDITrail/MTDashboard11.cpp")
    add_files("MIDITrail/MTTimeIndicator11.cpp")
    add_files("MIDITrail/MTPictBoard11.cpp")
    add_files("MIDITrail/DXNoteRain11.cpp")
    add_files("MIDITrail/MTKeyboardRain11.cpp")
    add_files("MIDITrail/DXNoteBoxRing11.cpp")
    add_files("MIDITrail/MTGridRing11.cpp")
    add_files("MIDITrail/MTTimeIndicatorRing11.cpp")
    add_files("MIDITrail/MTPictBoardRing11.cpp")
    add_files("MIDITrail/MTBackgroundImage11.cpp")
    add_files("MIDITrail/MTStars11.cpp")
    add_files("MIDITrail/MTVideoExporter.cpp")
    add_files("MIDITrail/MTVideoExportDlg.cpp")
    add_files("MIDITrail/DXRenderer11.cpp")
    add_files("MIDITrail/DXScene.cpp")
    add_files("MIDITrail/imgui_ja_gryph_ranges.cpp")
    add_files("MIDITrail/MIDITrailApp.cpp")
    add_files("MIDITrail/MIDITrailMain.cpp")
    add_files("MIDITrail/MTAboutDlg.cpp")
    add_files("MIDITrail/MTCmdLineParser.cpp")
    add_files("MIDITrail/MTColorCfgDlg.cpp")
    add_files("MIDITrail/MTColorConf.cpp")
    add_files("MIDITrail/MTColorPalette.cpp")
    add_files("MIDITrail/MTColorPaletteCfgDlg.cpp")
    add_files("MIDITrail/MTColorPickerDlg.cpp")
    add_files("MIDITrail/MTColorParamExportDlg.cpp")
    add_files("MIDITrail/MTColorParamImportDlg.cpp")
    add_files("MIDITrail/MTConfFile.cpp")
    add_files("MIDITrail/MTConfigManager11.cpp")
    add_files("MIDITrail/MTFileList.cpp")
    add_files("MIDITrail/MTFirstPersonCam.cpp")
    add_files("MIDITrail/MTFont2Bmp.cpp")
    add_files("MIDITrail/MTGamePadCtrl.cpp")
    add_files("MIDITrail/MTGraphicCfgDlg.cpp")
    add_files("MIDITrail/MTHowToViewDlg.cpp")
    add_files("MIDITrail/MTLogo11.cpp")
    add_files("MIDITrail/MTMIDIINCfgDlg.cpp")
    add_files("MIDITrail/MTMIDIOUTCfgDlg.cpp")
    add_files("MIDITrail/MTNoteDesign.cpp")
    add_files("MIDITrail/MTNoteDesignMod.cpp")
    add_files("MIDITrail/MTNoteDesignRing.cpp")
    add_files("MIDITrail/MTNotePitchBend.cpp")
    add_files("MIDITrail/MTNoteRipple.cpp")
    add_files("MIDITrail/MTNoteRippleMod.cpp")
    add_files("MIDITrail/MTPianoKeyboard.cpp")
    add_files("MIDITrail/MTPianoKeyboardDesign.cpp")
    add_files("MIDITrail/MTPianoKeyboardDesignMod.cpp")
    add_files("MIDITrail/MTScene.cpp")
    add_files("MIDITrail/MTWindowSizeCfgDlg.cpp")
    add_files("MIDITrail/stdafx.cpp")
    add_files("MIDITrail/MIDITrail.rc")

    -- ced 20260629: deploy resource folders next to the exe AFTER build, but only when
    -- they do not already exist. This keeps a fresh build dir runnable while NEVER
    -- overwriting an existing (user-customized) conf/data folder.
    after_build(function (target)
        local outdir = target:targetdir()
        for _, name in ipairs({"conf", "data", "doc"}) do
            local src = path.join(os.projectdir(), "Resources", name)
            local dst = path.join(outdir, name)
            if os.isdir(dst) then
                print("[deploy] skip Resources/%s (already exists at %s)", name, dst)
            elseif os.isdir(src) then
                os.cp(src, outdir)
                print("[deploy] copied Resources/%s -> %s", name, dst)
            end
        end
    end)
